// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcNrSBAb8ouJ29BgCA23eZNQ3xVUXiBM4',
    appId: '1:872363386799:web:0f01c6c223115a50baf15a',
    messagingSenderId: '872363386799',
    projectId: 'motioninternweek7',
    authDomain: 'motioninternweek7.firebaseapp.com',
    storageBucket: 'motioninternweek7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2YkTn0_dEPQW-IRz-sjSn921Iw8IUn4c',
    appId: '1:872363386799:android:4072d79f8962a154baf15a',
    messagingSenderId: '872363386799',
    projectId: 'motioninternweek7',
    storageBucket: 'motioninternweek7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ4fpIuIqRfKxeIa4FGpCQnYz5cTw3wB4',
    appId: '1:872363386799:ios:cceb1d079b665e97baf15a',
    messagingSenderId: '872363386799',
    projectId: 'motioninternweek7',
    storageBucket: 'motioninternweek7.appspot.com',
    iosBundleId: 'com.example.motioninternWeek7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ4fpIuIqRfKxeIa4FGpCQnYz5cTw3wB4',
    appId: '1:872363386799:ios:00b74c016148fd11baf15a',
    messagingSenderId: '872363386799',
    projectId: 'motioninternweek7',
    storageBucket: 'motioninternweek7.appspot.com',
    iosBundleId: 'com.example.motioninternWeek7.RunnerTests',
  );
}
